
export type Country = {
  id: string;
  name: string;
  capital: string;
};

export const COUNTRIES: Country[] = [
  { id: 'ru', name: 'Россия', capital: 'Москва' },
  { id: 'us', name: 'США', capital: 'Вашингтон' },
  { id: 'gb', name: 'Великобритания', capital: 'Лондон' },
  { id: 'fr', name: 'Франция', capital: 'Париж' },
  { id: 'de', name: 'Германия', capital: 'Берлин' },
  { id: 'it', name: 'Италия', capital: 'Рим' },
  { id: 'jp', name: 'Япония', capital: 'Токио' },
  { id: 'cn', name: 'Китай', capital: 'Пекин' },
  { id: 'in', name: 'Индия', capital: 'Нью-Дели' },
  { id: 'br', name: 'Бразилия', capital: 'Бразилиа' },
  { id: 'ca', name: 'Канада', capital: 'Оттава' },
  { id: 'au', name: 'Австралия', capital: 'Канберра' },
  { id: 'es', name: 'Испания', capital: 'Мадрид' },
  { id: 'mx', name: 'Мексика', capital: 'Мехико' },
  { id: 'ar', name: 'Аргентина', capital: 'Буэнос-Айрес' },
  { id: 'eg', name: 'Египет', capital: 'Каир' },
  { id: 'za', name: 'ЮАР', capital: 'Претория' },
  { id: 'ng', name: 'Нигерия', capital: 'Абуджа' },
  { id: 'kr', name: 'Южная Корея', capital: 'Сеул' },
  { id: 'tr', name: 'Турция', capital: 'Анкара' },
  { id: 'sa', name: 'Саудовская Аравия', capital: 'Эр-Рияд' },
  { id: 'id', name: 'Индонезия', capital: 'Джакарта' },
  { id: 'pk', name: 'Пакистан', capital: 'Исламабад' },
  { id: 'bd', name: 'Бангладеш', capital: 'Дакка' },
  { id: 'vn', name: 'Вьетнам', capital: 'Ханой' },
  { id: 'ph', name: 'Филиппины', capital: 'Манила' },
  { id: 'th', name: 'Таиланд', capital: 'Бангкок' },
  { id: 'ir', name: 'Иран', capital: 'Тегеран' },
  { id: 'iq', name: 'Ирак', capital: 'Багдад' },
  { id: 'pl', name: 'Польша', capital: 'Варшава' },
  { id: 'ua', name: 'Украина', capital: 'Киев' },
  { id: 'nl', name: 'Нидерланды', capital: 'Амстердам' },
  { id: 'be', name: 'Бельгия', capital: 'Брюссель' },
  { id: 'se', name: 'Швеция', capital: 'Стокгольм' },
  { id: 'no', name: 'Норвегия', capital: 'Осло' },
  { id: 'dk', name: 'Дания', capital: 'Копенгаген' },
  { id: 'fi', name: 'Финляндия', capital: 'Хельсинки' },
  { id: 'ch', name: 'Швейцария', capital: 'Берн' },
  { id: 'at', name: 'Австрия', capital: 'Вена' },
  { id: 'gr', name: 'Греция', capital: 'Афины' },
  { id: 'pt', name: 'Португалия', capital: 'Лиссабон' },
  { id: 'ie', name: 'Ирландия', capital: 'Дублин' },
  { id: 'nz', name: 'Новая Зеландия', capital: 'Веллингтон' },
  { id: 'sg', name: 'Сингапур', capital: 'Сингапур' },
  { id: 'my', name: 'Малайзия', capital: 'Куала-Лумпур' },
  { id: 'cl', name: 'Чили', capital: 'Сантьяго' },
  { id: 'co', name: 'Колумбия', capital: 'Богота' },
  { id: 'pe', name: 'Перу', capital: 'Лима' },
  { id: 've', name: 'Венесуэла', capital: 'Каракас' },
  { id: 'kz', name: 'Казахстан', capital: 'Астана' }
];
